<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DiscardTest</name>
   <tag></tag>
   <elementGuidId>967dabc8-4d37-44b8-85d1-cf678d8e680a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;grayLinkBtm&quot;]/a[text()=&quot;Discard&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;grayLinkBtm&quot;]/a[text()=&quot;Discard&quot;]</value>
   </webElementProperties>
</WebElementEntity>
