<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_screenElipsis</name>
   <tag></tag>
   <elementGuidId>86875b92-a3e4-4bc2-8d39-ef9ced659729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@id=&quot;step-image-2&quot;]/following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@id=&quot;step-image-2&quot;]/following-sibling::div</value>
   </webElementProperties>
</WebElementEntity>
