<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_ViewAndEditElipsis</name>
   <tag></tag>
   <elementGuidId>22a922c3-72a4-4757-a2d8-706fdac2d984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//img[@id=&quot;2&quot;]/following-sibling::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//img[@id=&quot;2&quot;]/following-sibling::div</value>
   </webElementProperties>
</WebElementEntity>
