<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>matchip_addedTag</name>
   <tag></tag>
   <elementGuidId>ce1de633-9671-4797-9dd9-11c6de49e513</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;mat-chip-list-wrapper&quot;]/mat-chip[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;mat-chip-list-wrapper&quot;]/mat-chip[1]</value>
   </webElementProperties>
</WebElementEntity>
