<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mouseHover_collapseDrawer</name>
   <tag></tag>
   <elementGuidId>c6a82d88-98ff-45bf-9f6c-113fb1cb346f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ng-lottie[@containerclass=&quot;ngLottieCollapseIcon&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ng-lottie[@containerclass=&quot;ngLottieCollapseIcon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
