<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_stop</name>
   <tag></tag>
   <elementGuidId>80c45857-5798-4c82-bb3c-6be6f94b72a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='actionItems']/a[@class='acceptTests']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='actionItems']/a[@class='acceptTests']</value>
   </webElementProperties>
</WebElementEntity>
