<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_DocReport</name>
   <tag></tag>
   <elementGuidId>b0a37f68-fa15-4bf1-8681-782398da02f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;actionItems&quot;]/a[@class=&quot;docReport&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;actionItems&quot;]/a[@class=&quot;docReport&quot;]</value>
   </webElementProperties>
</WebElementEntity>
