<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testCasesList</name>
   <tag></tag>
   <elementGuidId>cdcadb45-fefa-475c-b3f3-b8fe0e0cb2af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-test-results-tiles[@class=&quot;vScrollCards&quot;]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-test-results-tiles[@class=&quot;vScrollCards&quot;]/div</value>
   </webElementProperties>
</WebElementEntity>
