<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tags_DropDownList</name>
   <tag></tag>
   <elementGuidId>a7d27974-e27c-4ed3-b8af-81a22ff6d1ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class=&quot;dropdownWrap&quot;]/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class=&quot;dropdownWrap&quot;]/li</value>
   </webElementProperties>
</WebElementEntity>
