<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>testCase_OptionQueued</name>
   <tag></tag>
   <elementGuidId>0d8dcac0-f6b5-49db-aca4-a0c9d164b085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='textLinks']/a[text()[contains(.,&quot;Queued&quot;)]]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='textLinks']/a[text()[contains(.,&quot;Queued&quot;)]]</value>
   </webElementProperties>
</WebElementEntity>
