<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_baseLine</name>
   <tag></tag>
   <elementGuidId>aeaa4d9f-ab23-4dc2-8af1-b54178659505</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;titleSection&quot;]/div/div[starts-with(@class,&quot;deviceName&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;titleSection&quot;]/div/div[starts-with(@class,&quot;deviceName&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
