<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_Recorded</name>
   <tag></tag>
   <elementGuidId>7de75867-5bb9-42e1-af4f-c02885511285</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tileStream']/a/div[@class='mat-card-title']/span[@title='Test']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tileStream']/a/div[@class='mat-card-title']/span[@title='Test']</value>
   </webElementProperties>
</WebElementEntity>
