<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_redo</name>
   <tag></tag>
   <elementGuidId>cc4e0ea6-e89e-49e2-a2ef-6d1d5b4f5686</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='tileStream']/a/div[@class='mat-card-title']/span[@title='Test_redo_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='tileStream']/a/div[@class='mat-card-title']/span[@title='Test_redo_1']</value>
   </webElementProperties>
</WebElementEntity>
