<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_PhysicalAndroidDevices</name>
   <tag></tag>
   <elementGuidId>b1e70848-ded8-444a-987d-1112a52923be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'Android')]/parent::div/following-sibling::div/div[contains(@class,'physical')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'Android')]/parent::div/following-sibling::div/div[contains(@class,'physical')]</value>
   </webElementProperties>
</WebElementEntity>
