<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_Rebooting_FirstDevice</name>
   <tag></tag>
   <elementGuidId>43d61b5e-7694-42d6-a7f3-d665b1ccca75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'list')]/div[1]/descendant::div[@class='statusText']/div[contains(text(),'Rebooting')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'list')]/div[1]/descendant::div[@class='statusText']/div[contains(text(),'Rebooting')]</value>
   </webElementProperties>
</WebElementEntity>
