<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>taskAwaitingADevice_removeSingleTest</name>
   <tag></tag>
   <elementGuidId>bcd017df-3647-4fca-be42-b8194c163243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@containerclass=&quot;blackSmallPopover&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@containerclass=&quot;blackSmallPopover&quot;]</value>
   </webElementProperties>
</WebElementEntity>
