<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tasksAwaitingADevice_serachIcon</name>
   <tag></tag>
   <elementGuidId>7a81a2fb-f7aa-4f76-a676-c769887910a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;searchfield&quot;]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;searchfield&quot;]/div/span</value>
   </webElementProperties>
</WebElementEntity>
