<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-InviteUsers</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>fdac0870-f4c4-4b32-a432-d859b7a9098c</testSuiteGuid>
   <testCaseLink>
      <guid>6ab1c8e8-cf09-48e6-82ad-473319347aa8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e032c4-37bf-4ea6-a507-1ed36b9d9c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2d2cc9-3a88-4611-9a18-872caceedb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ea3198-2571-4da4-8322-04c5c42de5f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07743bd-4114-432d-bc6a-7023f190b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b2e96-a401-44e2-8d6f-05d402675be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3f0b32-0b03-4295-a003-b8f0cbece597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d7e190-afba-483e-9cba-7ccc69422b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564ba218-0c9f-42c0-8882-a31dd35ac9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfc8df6-c96b-4f58-82ee-65a2d75fb0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fe48cc8-de15-4e3b-a507-d9516a0e7da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6c61e0e-a7e3-4d77-9d24-e8eaf80dfba6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/InviteUsers/MS-Invite-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>86108e2d-2c45-4efd-8189-4fa2165df423</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/InviteUsers/Invite</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2546fd1-c066-42e8-90a6-4c02a9bdd36f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab485b59-102e-468d-855e-3b23ea226473</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7acabd93-e317-4c3f-9af1-6a2cf4083813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c7c3287-5d69-4f53-8803-fcac2f4e905e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>86108e2d-2c45-4efd-8189-4fa2165df423</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>emailAddress</value>
         <variableId>3ce57edc-9a83-4c5c-bcb2-e6a045389a51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2596709b-b73a-493a-a412-d02408ca15ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56332647-7452-4a16-9571-186a344ea398</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cb5ff7e-4894-4181-9bd7-799bf5c30ad1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa2a3959-da03-4811-8d01-b605a4872482</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/InviteUsers/MS-Invite-02</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9f119e6e-e070-4bd8-8bff-6b2c77b6bf68</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/InviteUsers/Invite</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aa728cc-a1ec-4220-9240-a32f38c7b26d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ba4763f-af44-499e-8e52-8f48baa25869</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4d4dfc3-adfa-4b7f-a430-91787bf4b694</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a87b18de-731f-49f6-8140-c87c35489641</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9f119e6e-e070-4bd8-8bff-6b2c77b6bf68</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>existingEmailAddress</value>
         <variableId>726d0164-d23c-4877-97dc-08544cd36fef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba6d005c-a473-465c-8f77-f3de2ba0031c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10acce00-73aa-4783-a8c5-66899613c0d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16ff7883-29b3-4f39-a621-1b9bca0d45dc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
