<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-CreateNewTestCase</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>90fb0d59-ecec-474a-a3fc-8e06845b146c</testSuiteGuid>
   <testCaseLink>
      <guid>be563bd0-462c-4cea-ba41-e61ac66ff094</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e032c4-37bf-4ea6-a507-1ed36b9d9c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2d2cc9-3a88-4611-9a18-872caceedb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ea3198-2571-4da4-8322-04c5c42de5f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07743bd-4114-432d-bc6a-7023f190b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b2e96-a401-44e2-8d6f-05d402675be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3f0b32-0b03-4295-a003-b8f0cbece597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d7e190-afba-483e-9cba-7ccc69422b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564ba218-0c9f-42c0-8882-a31dd35ac9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfc8df6-c96b-4f58-82ee-65a2d75fb0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fe48cc8-de15-4e3b-a507-d9516a0e7da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7c6041e-1151-4eaa-afec-709895887dcd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/CreateNewTestCase/MS-CreateNewTestCase-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5c62395c-88f2-48b8-89d5-fcbff5ef1341</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>5c62395c-88f2-48b8-89d5-fcbff5ef1341</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>1683bd5f-86d1-47ca-baff-70e38548a76b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5c62395c-88f2-48b8-89d5-fcbff5ef1341</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>9933121a-59b4-410d-b5f8-c36584c1323c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5c62395c-88f2-48b8-89d5-fcbff5ef1341</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>ee3aa253-13cc-4a27-a816-6da37dfb625e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5c62395c-88f2-48b8-89d5-fcbff5ef1341</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>897b437b-2e1a-47ba-b3dc-aecc2e911d2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13328ed2-802f-4d6d-a6be-d07e66710165</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41cdbfa5-e9d8-476c-b622-ed510cfcd4f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f135fdc8-285d-4288-b391-62a6fa7ba65d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a46e12c7-a23b-4f88-918e-70f991e362b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9074b79e-68d6-4e95-be98-03d05626dbd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4a1df54-08a7-40c9-a115-d82eab65369f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e623eb4-6f16-4bdc-a153-70a72e364d1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b33e47e-f47b-4709-a2f3-ca117d77731c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9783c0a7-b7ef-4a3e-aa2a-6f72cb003582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f97bae75-e08b-4763-b155-9c6826afc4ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a13fca7-a3f5-46df-8078-619c6a3c3134</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6de764-c5bb-4ef1-bf0f-3692693d8c43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ced165c-e0e4-4773-86f8-da2505c3a1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269be403-5c74-45b1-af10-6764c7a9a1c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75850cd3-e910-4d64-b77e-6b8d0acd0c64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7050550b-4254-416d-8c83-0a26ecbad4b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7d21306-e6e7-45cf-b0f3-d9efa502e72e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae45467d-b440-43f0-8003-58f6538225e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>587edfc4-b8f8-44a8-bc49-044acc6ca9f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57e99b88-76ec-4e55-b1a6-3d415390c67c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d88103c5-f9a9-4cce-95a0-adb501c3cf17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e110bb43-0926-4e28-9123-8f2dc294389c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07ccb1ff-e283-4c0a-854e-9c4b05032950</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f1818c3-5c57-412d-94b1-2e5cf691056e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f695109f-4dfa-49c1-9f0c-cd2787f03838</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a906477-fab8-4bd4-9aab-854f9b49b08c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>623e4ecd-4ea9-4c03-bf4a-d92cbd86f3be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d1e589d-cdb3-4f21-8157-cbce1ab32d91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03913e3a-53dc-46c2-8ed7-58f952963682</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a8cc12-adc2-4a46-b75c-414a389dbc0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b6980b-c34b-4862-b67c-59dd10fdb813</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d034a326-9429-446c-a270-c7919b703b03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>657df220-d0f8-4e70-b2d9-eb7a8ed8dc81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f61756f-26ac-4d4e-a549-f2de22703695</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b4abec6-47b6-45dd-9e82-f8d140673335</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>237592e9-f012-4083-866b-49f0a2ffb7ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cee96d2c-3f59-4b13-afbb-ddff0667c548</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8914453a-62fb-431a-93f8-e3c4fde376d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bf9c0f0-3459-41b6-85e6-ed99693c6123</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec80e0f5-bc21-4d42-ae9d-65aa17a48d22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>176ebaf7-9ce6-47d0-a310-9b830f37a515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0cac0223-dc6e-4f3c-94cc-a231c59dcbaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39cfc731-c9ab-44c0-b505-b6a5a71e9c95</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/CreateNewTestCase/MS-CreateNewTestCase-03</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>717be39a-1ca4-4788-896c-cb1acd73cabf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>717be39a-1ca4-4788-896c-cb1acd73cabf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>973d0637-b17b-4618-8cd3-e3a84410c936</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>717be39a-1ca4-4788-896c-cb1acd73cabf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>2ec364d9-8606-4ed5-aca6-10cffe255037</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>717be39a-1ca4-4788-896c-cb1acd73cabf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>8d74c330-5fa8-4c4f-9fc6-d42804a2b1f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>717be39a-1ca4-4788-896c-cb1acd73cabf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>bd0d62f2-8c14-4cce-b222-e781c5e8ee49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0441eb25-77d1-4776-9697-fa37be98ef54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e29ddda-1605-4e99-a962-3156e837b2b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a17b396-3463-4840-8286-7aab59fc3ff4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd74ce59-1bab-4b2b-a96b-1a19831404e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75d4560e-1b27-4687-922c-b938d6835de8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83effeb3-ec2e-4996-b4b9-ccd9d55fa5af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f20f116e-52e6-4212-bd42-9a68a172bb7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0f7dcca-3895-449d-972a-7f1ea81e5246</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfe6d8e3-d126-470e-82b4-72e5f263d241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>901ff2e6-0b3e-4b5b-b916-ed821acbd719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbe799f2-c756-492e-b4d1-9808bc529253</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c393a604-be69-4e29-8862-7ec13adde948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e481cc6f-b091-4b06-ae9f-72626ef477eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5472316-615c-4d8e-8bba-6f4192b54d4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8821280-d461-454f-ae2b-5afc76a3428b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04208a75-472b-4fe1-8df0-29ec416c72a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3b8d243-57a8-421f-9805-4bc67b8bc953</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0722d904-0de9-49ca-a313-1e384b0604c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc4d545e-4d09-4520-8889-b037d99e5964</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18fda797-b039-4758-a4e4-e400249cdbe1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5eeebe47-2b23-4ca2-96cb-a9799fd2eb40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8ffb794-0784-47db-a5f9-16e12d8a4c07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60613c72-65ec-4436-be07-7f16c48b9585</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/CreateNewTestCase/MS-CreateNewTestCase-04</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c1b84292-7c7d-4d35-a107-369b1024fe0e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>c1b84292-7c7d-4d35-a107-369b1024fe0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>fffadf38-2d69-441b-baff-fe143b5ab82d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c1b84292-7c7d-4d35-a107-369b1024fe0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>8da93780-dbbc-4f96-b8d9-8756a6c56663</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c1b84292-7c7d-4d35-a107-369b1024fe0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>eed8379b-60a8-49bb-9f28-2efbecf604d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c1b84292-7c7d-4d35-a107-369b1024fe0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>85d3767a-8873-48d4-bc08-bbc14a94b8ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df56502c-482f-47d1-afcd-0ceadf81a2dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da55075c-6820-4a4d-950a-7b4b64c964c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>59bb722e-8c43-4666-a519-51121a35f518</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17ba4c84-903d-480b-ad0f-a34378c6a3a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f38ef0b-ea4d-4eaf-8a58-9dc4ba0d3fd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c7e5fbe-64be-45c8-880f-d4608e5750e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bffabe22-4166-4b95-8968-78d5e6bd0891</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e37d3ca9-e2bc-47d4-858e-6340e0cad53c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb7a8c1c-4fd2-4159-954a-ee1f6be38849</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24721284-802e-4354-a0b5-7324ddccfe0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>812b58e6-6b74-4ce4-9535-3d40c13e1b45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>011d5497-8e07-49e0-a5bc-7477d1a0628e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ae7dbac-b826-425e-b157-0878bbd58c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>930978ce-e31a-4b7e-830f-a6b76930b8bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2bf8fb79-3ddc-4e21-976e-1201a5ef6276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b319650c-aee8-4552-9f6b-9e2e87ba1b6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f69fa65-4a54-4f9a-adad-b7939e09f3db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ee712a9-b7fa-4610-ab2d-66da177c35ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96e88a2f-9f37-4c59-9eb4-c58c31668e28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c91d87db-747a-4238-a7ed-6c29832abaaa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3bd2bc0c-cf04-4fc7-9e75-3ac8a63d5f7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f7f3a93-3d2a-4999-8fe1-3700b6292ad6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c096e6-a0bf-4f82-9f9f-ac9085e75e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52e8ba03-bc30-40ac-90d3-4822fe541768</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef98e46-c6bd-406e-adeb-d5aec9363e51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83cb23d2-30b6-4803-9f4e-a962698e38ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd99ecc-8a49-4856-b551-08edeb06d5b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>137fd5b6-ddf0-4a2e-b14f-b4f68cd2b3af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cf80025-93c9-4c64-88a7-e4a9bfeeb832</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6dbc003-8120-477b-bf57-5a477909ae25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39aa2314-4134-430a-82d1-0ac7c1602827</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5a08288f-ed55-4ec3-beef-fb9cd3af80f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Obsolete/MS-CreateNewTestCase-05</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9ea77616-f036-4044-9cca-04cc5e370837</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9ea77616-f036-4044-9cca-04cc5e370837</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>1cf0be83-88d7-42e7-82b4-a1ba5298a948</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ea77616-f036-4044-9cca-04cc5e370837</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>c0b48043-2352-4df3-9d37-4d630149926e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ea77616-f036-4044-9cca-04cc5e370837</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>5d89c556-8c2c-4c37-b838-6e0e9de836e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9ea77616-f036-4044-9cca-04cc5e370837</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>c3277fcd-1f8f-4be1-87bd-42cdfa5b1e58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eda0829-37a1-4970-b947-486333d4b515</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecaff304-8f87-4eaa-a1d0-cf2f4395202b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>902fc530-907d-4908-869a-6dfaac75b001</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8899f2c2-7d64-49af-9e59-bc1510439cd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa12d7bb-8e34-4147-9cac-90681793b4cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6abfc15-a778-4b23-8197-02d037d0dbd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5ba69c0-14fb-4222-9b28-50e1a98e5452</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba559687-44e8-4de1-a0dd-f6647e838c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4d70102-b2e4-45cc-bbfd-fbb8fc625a74</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18cf2d26-8aaa-4898-851c-8ec8065e01ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00c6e894-41b9-4d3d-a07e-fe5467540546</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c2ee2b8-eec4-405c-a1e8-76b124c4951d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a2f9fe-f833-427b-bb30-e6fa0bb94792</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bbc6065-28cd-4f11-b4a4-0d6863cbd039</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e626dd-8de2-4581-972f-a76adc52c766</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7566003-4ce8-4af6-866f-bf0c289caeb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6de718a3-7331-4bf2-8fca-6c2da20c2a43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e653857a-9a42-410b-92e6-66766e4388f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19337a7e-ba98-42e4-8628-80fedfc99a37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6754b093-1ac8-475d-930f-63272c641e37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec4b3bca-3ec6-4f0d-ada2-5c0cd793d49a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0a999af-4822-4973-8d6a-db43e3ff828b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4731bab7-591e-4882-8149-b2f45af97f07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d26591c-8f2c-4ba9-9509-6f6dfb3ff285</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de4f5d0d-6e50-4611-bba7-654ff52208da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32ecf910-ea1e-4214-8151-9407208660d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7498c7de-0f82-4182-991c-a5c662dee544</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b7e36c8-47ce-4491-ad55-7efc9239d7fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cf3d6b1-a2f1-4bac-9f6a-4c4fc5d46977</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d198a513-735c-4e28-8f5c-3890e3ebbea9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64cf8f8e-7981-4471-b766-581c5c1d43ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/CreateNewTestCase/MS-CreateNewTestCase-02</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6e9ea70a-f4e2-40f8-8325-e13009e15dd3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6e9ea70a-f4e2-40f8-8325-e13009e15dd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>b5e32c2c-31e9-4414-9996-fb5da3f3c5c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e9ea70a-f4e2-40f8-8325-e13009e15dd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>60fc877c-0ad9-4c35-8af0-3f0748c1278a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e9ea70a-f4e2-40f8-8325-e13009e15dd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>2b27bee4-9ad3-4da5-bb37-c27aa55cd4e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6e9ea70a-f4e2-40f8-8325-e13009e15dd3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>a5f7fa27-4ed1-44ac-8a18-e08a17da5bc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f7f408d-346a-4013-a9e4-651589dc8cc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2079c67b-baa6-43cd-875e-83b7d866c44f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff929189-82a3-40c0-914f-62626a7861f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3efd9fea-0944-4c39-b07a-bcd87aa500dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3efc0111-8782-4ab1-ab33-1dfb22ff2282</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d3519b2-a903-4090-8003-a6e9afe0be77</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9678391-22e6-4c7a-969c-ddb05af99b83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd2c22d-51bf-4913-a224-65f269e65377</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e50667-673f-41ad-9b26-0efef433fbcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcf09ee3-0b4e-434d-bfe7-cc34c2cb0fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c03c92f-7fa5-43e2-afd5-be2f96394301</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>412a8210-b88f-4d76-8686-4a5c4a4b5567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5e0ca5b-203d-4a1c-ae6f-657dbdb18341</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd9369bb-9851-4ee9-8dab-923ac783b1e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de9ae86-39cd-4da5-9744-0d7a0d3e1bf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5674504-122c-4d2c-ac4e-246ce95e2b43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8c050be-ddda-42b6-a821-0e421227dc89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c94b8700-9b12-4d78-817d-cd96563fd60b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7df17f59-a9a2-411a-9f29-e06f46c8a20f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2274b36b-3944-49b9-9572-e9e4fe15bfce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f698d33-4034-403c-b00a-b5b0a1eeabb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72987cd6-415f-4ee9-99d1-6979ac332355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cecdf853-088c-4383-b14f-6fbfab3b244c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6988e710-43d4-4fd3-adf8-be6fd7e43cc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31f8e56d-3c5e-4924-9c56-ee44167f039b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>782ac202-ff73-4fee-acac-bed9a02eab79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86218a4d-bc69-45e2-8daa-3906a8916442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45a04a92-ee34-40d7-a923-5376376a64f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5f41784-37cc-492a-af7f-67d961e5adc5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a28b18f4-3f7f-4f11-a515-3ba98d2e374d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f5b7f7f-5941-48fc-ab9e-0a9589744819</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c67ce336-e77b-4c95-bb28-290506696b13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a04710c0-b653-4159-84d4-31943720b368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be7f0628-f1d3-43d3-9622-cff87055b78e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34965935-bb61-45ad-b6bb-6e6b1bed3861</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d901b5-fdcb-41d9-ad09-5b9c58804de4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35f22f26-f100-4894-9bd5-568389e52393</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d40e95a5-21af-4d1d-897d-c41464716910</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ff5ff39-d851-4df4-8601-b860b7ed3862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f7f33d0-e7c5-46c2-b091-21c9910c7405</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b8fa684-cc6c-4aeb-8aa7-4c6751d4849d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>443095fd-e5e3-456b-89b2-a47acdf2c1ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f71ac9f-3153-4909-9749-4c2f1fabac87</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>222db757-3910-4a71-ac95-b44c7d7f98b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b188d382-a45c-4368-9703-01a5cd55d51e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0226325-c237-4f68-b0b6-a2b8752e25f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b834f3f4-d506-41db-8e06-de37daf6c8a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8de7b069-1d2a-459d-93bd-9a97dd9504cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8052a455-4124-43f6-a841-acbe660e5399</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77d98f4d-4bbc-4868-b085-10f2bd92f6c6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
