<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YesOnDeletingRecoTest-ConfirmationWindow</name>
   <tag></tag>
   <elementGuidId>d4ebe278-97f6-4028-ae7b-ce640d1ca32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button/span[contains(text(),'Yes')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button/span[contains(text(),'Yes')]</value>
   </webElementProperties>
</WebElementEntity>
