<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_TCTitle</name>
   <tag></tag>
   <elementGuidId>9b4a6a37-5a71-4428-97ed-85603f53a669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;title&quot;]/span[@title=&quot;MS-ManageTest-02&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;title&quot;]/span[@title=&quot;MS-ManageTest-02&quot;]</value>
   </webElementProperties>
</WebElementEntity>
