<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_openRunAllTestCasePopup</name>
   <tag></tag>
   <elementGuidId>603abef3-618b-43b8-8b71-0f114135d543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='actionItems']/a[@class='refresh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='actionItems']/a[@class='refresh']</value>
   </webElementProperties>
</WebElementEntity>
