<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_InputDataArea</name>
   <tag></tag>
   <elementGuidId>f191f17e-7efb-4a0e-b575-1c74ef35744f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='dataArea']/div[@class='mat-chip-list-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='dataArea']/div[@class='mat-chip-list-wrapper']</value>
   </webElementProperties>
</WebElementEntity>
