<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_testCaseBar</name>
   <tag></tag>
   <elementGuidId>c90678c2-0b77-4edd-aeae-d4bd423de0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]</value>
   </webElementProperties>
</WebElementEntity>
