<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_tested</name>
   <tag></tag>
   <elementGuidId>a2820cf1-7f3d-410a-bd61-ad208365037d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'Tested')]/following-sibling::div[@class='screen']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'Tested')]/following-sibling::div[@class='screen']/img</value>
   </webElementProperties>
</WebElementEntity>
