<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_baseline</name>
   <tag></tag>
   <elementGuidId>aebc0b89-89dc-4aa1-b911-d8da181ad6bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'Baseline')]/following-sibling::div[@class='screen']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'Baseline')]/following-sibling::div[@class='screen']/img</value>
   </webElementProperties>
</WebElementEntity>
