<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>info_FirstInUseDevice</name>
   <tag></tag>
   <elementGuidId>1bdd5864-d684-458d-8742-11465be2f8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'list')]/div[1]/descendant::div[@class='statusText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'list')]/div[1]/descendant::div[@class='statusText']</value>
   </webElementProperties>
</WebElementEntity>
