<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>info_Device</name>
   <tag></tag>
   <elementGuidId>f9c2e035-7b18-44dd-8948-80ce9d0aed56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='infoDiv']/strong[contains(text(),'Device:')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='infoDiv']/strong[contains(text(),'Device:')]</value>
   </webElementProperties>
</WebElementEntity>
