<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_testCaseAssignee</name>
   <tag></tag>
   <elementGuidId>06a18ebf-5fdc-46f9-9bf0-cfeb8200d1fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]/descendant::span[@class=&quot;userName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]/descendant::span[@class=&quot;userName&quot;]</value>
   </webElementProperties>
</WebElementEntity>
