<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_ClonedTC</name>
   <tag></tag>
   <elementGuidId>bab22576-1a38-48c5-840a-43648d23f09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;title&quot;]/span[contains(text(),'MS-ManageTest-02-clone')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;title&quot;]/span[contains(text(),'MS-ManageTest-02-clone')]</value>
   </webElementProperties>
</WebElementEntity>
