<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tc_broken</name>
   <tag></tag>
   <elementGuidId>199fea28-a263-4124-9926-705a0cb134fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[text()=&quot;broken&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[text()=&quot;broken&quot;]</value>
   </webElementProperties>
</WebElementEntity>
