<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tc_failed</name>
   <tag></tag>
   <elementGuidId>6668c83a-6068-4fec-84a1-cd26ac6106cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[text()=&quot;failed&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[text()=&quot;failed&quot;]</value>
   </webElementProperties>
</WebElementEntity>
