<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Defects</name>
   <tag></tag>
   <elementGuidId>8bab95bc-f71e-45b5-a7c3-e4d4eebe56f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[contains(text(),'defects')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[contains(text(),'defects')]</value>
   </webElementProperties>
</WebElementEntity>
