<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_loginToContinue</name>
   <tag></tag>
   <elementGuidId>9bdd97af-eb19-4bb3-a6b8-fba21648c66f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/section/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-bwzfXH cJYcBP&quot;]/div[@class=&quot;sc-htpNat iNnOlb&quot;]/div[@class=&quot;sc-bZQynM bskBNX&quot;]/div[@class=&quot;sc-jWBwVP EghCw&quot;]/div[1]/section[@class=&quot;sc-eHgmQL jGuQRd&quot;]/div[@class=&quot;sc-hSdWYo cNXylC&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-hSdWYo cNXylC</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log in to continue to:MQ-103</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-bwzfXH cJYcBP&quot;]/div[@class=&quot;sc-htpNat iNnOlb&quot;]/div[@class=&quot;sc-bZQynM bskBNX&quot;]/div[@class=&quot;sc-jWBwVP EghCw&quot;]/div[1]/section[@class=&quot;sc-eHgmQL jGuQRd&quot;]/div[@class=&quot;sc-hSdWYo cNXylC&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/section/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div</value>
   </webElementXpaths>
</WebElementEntity>
