<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_tooltipUDID</name>
   <tag></tag>
   <elementGuidId>57b8c3a1-a679-4fa1-9c9e-fe0fd3b7ce14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tooltip/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tooltip/div</value>
   </webElementProperties>
</WebElementEntity>
