<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_PlayVideoCompleted</name>
   <tag></tag>
   <elementGuidId>48852ceb-c4f1-410c-b747-1b72f42b8e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-progress-bar[@aria-valuenow='100']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-progress-bar[@aria-valuenow='100']</value>
   </webElementProperties>
</WebElementEntity>
