<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>appMap_deviceOS</name>
   <tag></tag>
   <elementGuidId>f280349a-86be-471e-90ab-f6ff64d83d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;deviceDetails&quot;)]/div[@class=&quot;infoText&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;deviceDetails&quot;)]/div[@class=&quot;infoText&quot;]</value>
   </webElementProperties>
</WebElementEntity>
