<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_watchReplayAfterCompleteCrawl</name>
   <tag></tag>
   <elementGuidId>33a74dea-ec95-49e7-8567-5f1cc20d9d1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'notifyButton')]/a[contains(text(),'Watch')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'notifyButton')]/a[contains(text(),'Watch')]</value>
   </webElementProperties>
</WebElementEntity>
