<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SettingsResumeOption</name>
   <tag></tag>
   <elementGuidId>09dd96d2-fa71-4963-a1ed-631542f4f386</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@class,'dropdown')]/span[text()='Resume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,'dropdown')]/span[text()='Resume']</value>
   </webElementProperties>
</WebElementEntity>
