<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_SettingsPauseOption</name>
   <tag></tag>
   <elementGuidId>c48db4dc-60d4-43b9-9a0e-398eb626abb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(@class,'dropdown')]/span[text()='Pause']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(@class,'dropdown')]/span[text()='Pause']</value>
   </webElementProperties>
</WebElementEntity>
