<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_previewOnWatchVideo</name>
   <tag></tag>
   <elementGuidId>fcba27fc-0f11-4780-8f3f-0353221c227f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'swiperSection')]/div[contains(@class,'swiper')]/descendant::div[contains(@class,'active')]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'swiperSection')]/div[contains(@class,'swiper')]/descendant::div[contains(@class,'active')]/img</value>
   </webElementProperties>
</WebElementEntity>
