<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_logsDropdown</name>
   <tag></tag>
   <elementGuidId>171ac932-ab1a-48c0-a637-0fd437d19568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(@class,'dropdown-popover-value')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(@class,'dropdown-popover-value')][1]</value>
   </webElementProperties>
</WebElementEntity>
