<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>selected_CrawlTimeFromHistory</name>
   <tag></tag>
   <elementGuidId>ecc40615-7329-40fa-ab18-52a54b40534a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'purpleHead')]/div[contains(text(),'Initiated')]/following-sibling::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'purpleHead')]/div[contains(text(),'Initiated')]/following-sibling::div[1]</value>
   </webElementProperties>
</WebElementEntity>
