<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Configured</name>
   <tag></tag>
   <elementGuidId>f0f33bf2-8ee9-4be9-a722-b8e1591d4026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'completed')]/div[contains(text(),'Configured')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'completed')]/div[contains(text(),'Configured')]</value>
   </webElementProperties>
</WebElementEntity>
