<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tooltip_History</name>
   <tag></tag>
   <elementGuidId>6bdf0c34-017e-4a5a-b045-02dd123a8609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tooltip/div[contains(text(),'History')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tooltip/div[contains(text(),'History')]</value>
   </webElementProperties>
</WebElementEntity>
