<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_NoOnConfirmationWindow</name>
   <tag></tag>
   <elementGuidId>f607bdf1-0502-47c6-be27-0d2c73a08824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button/span[text()=&quot;No&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button/span[text()=&quot;No&quot;]</value>
   </webElementProperties>
</WebElementEntity>
