<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>b3f273e8-1f0a-455c-844d-f87997866991</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search our articles</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;intercom-container&quot;)/div[1]/div[1]/div[@class=&quot;intercom-messenger intercom-messenger-home-screen intercom-9zqtqz e16fp1gy0&quot;]/div[@class=&quot;intercom-1xafcqx e8111ny0&quot;]/div[@class=&quot;intercom-home-screen intercom-1a6uzeh ejdnm0c1 intercom-messenger-body-view-appear-done intercom-messenger-body-view-enter-done&quot;]/div[@class=&quot;intercom-u5foh5 ejdnm0c2&quot;]/div[@class=&quot;intercom-1clbhc1 ejdnm0c3&quot;]/div[1]/div[@class=&quot;intercom-home-screen-messenger-card intercom-home-screen-messenger-card-0 intercom-0 ejdnm0c0 intercom-messenger-card-failed-animation-appear-done intercom-messenger-card-failed-animation-enter-done&quot;]/div[@class=&quot;intercom-messenger-card-wrapper intercom-r18meb eoau2rn0&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;intercom-messenger-card-body intercom-icbmz8 e6v5kix0&quot;]/div[@class=&quot;intercom-zteh7t e1hl8kc40&quot;]/div[1]/div[1]/div[@class=&quot;intercom-messenger-card-component&quot;]/div[@class=&quot;intercom-0 e1kgnu3v0&quot;]/div[1]/div[@class=&quot;intercom-1qgdrjz ea4em4b0&quot;]/div[1]/input[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR_Help/NewPageResources/iframe_Latest Run_intercom-messenger-frame</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='intercom-container']/div/div/div/div[3]/div/div/div[3]/div/div/div/div/div/div/div/div/div/div/div/div/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
