<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-LogIn</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>335f800d-dc17-4d1d-8505-563dc330c818</testSuiteGuid>
   <testCaseLink>
      <guid>9735feb3-29e2-4f1f-884a-0ab90bc76e86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-02</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef6378fa-184c-44bc-806d-9e308d6dea0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c23957-15ba-4f86-9674-a985a9629935</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a54936ea-a34a-40a1-9c31-bc860a47db8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bfcaa0e-ebff-444e-9c2c-3d8aeb36839f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93229e0d-5bfc-4594-8ebc-5a5aae80590b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12112895-803d-48e9-aea0-d353b594a556</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f73748a3-637d-40a2-8825-ca689b08e8b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d90f6fc9-5ec8-45d6-ab41-99f6be4e566a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f148cd5-8427-472b-8a2b-3dcac38bb8c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d9bce7a-01fd-4ea6-a8d0-94c5049cc1fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33331b78-5304-4ccd-b00d-aca44e162e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>111f50db-462f-4f9f-8e2a-65dab1357c25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>68b8fb41-45fa-4b90-913a-5c1f38bd15f3</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-4</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e032c4-37bf-4ea6-a507-1ed36b9d9c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2d2cc9-3a88-4611-9a18-872caceedb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ea3198-2571-4da4-8322-04c5c42de5f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07743bd-4114-432d-bc6a-7023f190b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b2e96-a401-44e2-8d6f-05d402675be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3f0b32-0b03-4295-a003-b8f0cbece597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d7e190-afba-483e-9cba-7ccc69422b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564ba218-0c9f-42c0-8882-a31dd35ac9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68b8fb41-45fa-4b90-913a-5c1f38bd15f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>fdfc8df6-c96b-4f58-82ee-65a2d75fb0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>68b8fb41-45fa-4b90-913a-5c1f38bd15f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>0fe48cc8-de15-4e3b-a507-d9516a0e7da7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
