<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Comments</name>
   <tag></tag>
   <elementGuidId>ebd6c48e-efd6-4551-bccd-c9f861a28243</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]/descendant::span[@class=&quot;commentsTxt&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;devicesWrap&quot;]/descendant::div[1]/descendant::span[@class=&quot;commentsTxt&quot;]</value>
   </webElementProperties>
</WebElementEntity>
