<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_passed</name>
   <tag></tag>
   <elementGuidId>b6533f0b-eca5-4ad9-bd9a-40050ad2ca76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[text()=&quot;passed&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[text()=&quot;passed&quot;]</value>
   </webElementProperties>
</WebElementEntity>
