<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_broken</name>
   <tag></tag>
   <elementGuidId>edbd2c2b-12cb-4fe2-9869-9e263231090c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[text()=&quot;broken&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[text()=&quot;broken&quot;]</value>
   </webElementProperties>
</WebElementEntity>
