<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath_numberOfCheckBoxes</name>
   <tag></tag>
   <elementGuidId>a6cbea11-e658-40fe-8b0f-2258630b6f86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-manage-test-case-list/div/div[@class=&quot;roundCheckBox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-manage-test-case-list/div/div[@class=&quot;roundCheckBox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
