<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_selectAllReplayTCs</name>
   <tag></tag>
   <elementGuidId>c4fe74a2-d905-4161-a71d-16e7b6bb8010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[contains(@for,&quot;selectall&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[contains(@for,&quot;selectall&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
