<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_error</name>
   <tag></tag>
   <elementGuidId>1a7de3ac-1b98-4e73-af68-921c85b878a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-card[contains(@class,&quot;review&quot;)]/mat-card-content/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-card[contains(@class,&quot;review&quot;)]/mat-card-content/div[1]</value>
   </webElementProperties>
</WebElementEntity>
