<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_crawlHistory_recommendedTests</name>
   <tag></tag>
   <elementGuidId>8b51502a-85c1-4aed-b489-572d4d2bec6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),&quot;Recommended&quot;)]/parent::div/following-sibling::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),&quot;Recommended&quot;)]/parent::div/following-sibling::div[1]</value>
   </webElementProperties>
</WebElementEntity>
