<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_crawlHistory_Device</name>
   <tag></tag>
   <elementGuidId>7409b443-97c0-4eb4-9186-5a0cfce05b6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),&quot;Device&quot;)]/following-sibling::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),&quot;Device&quot;)]/following-sibling::div[1]</value>
   </webElementProperties>
</WebElementEntity>
