<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_crawlHistory_Initiated</name>
   <tag></tag>
   <elementGuidId>1da20a85-ed79-43fe-8f5e-e1c94e132422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),&quot;Initiated&quot;)]/following-sibling::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),&quot;Initiated&quot;)]/following-sibling::div[1]</value>
   </webElementProperties>
</WebElementEntity>
