<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialogue_Assertion</name>
   <tag></tag>
   <elementGuidId>7dd4d4ff-b554-4665-90d5-fd18555573de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//test-result-detail-dialog/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//test-result-detail-dialog/div</value>
   </webElementProperties>
</WebElementEntity>
