<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_dateTime</name>
   <tag></tag>
   <elementGuidId>c2866629-60c4-4b6a-9e24-928108893311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;projectDD&quot;]/div[@class=&quot;builds-list&quot;]/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;projectDD&quot;]/div[@class=&quot;builds-list&quot;]/div/div/div[2]/div[2]</value>
   </webElementProperties>
</WebElementEntity>
