<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RS-TestResult</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4a773a72-2394-4ee6-b81b-2a6ac7568fc9</testSuiteGuid>
   <testCaseLink>
      <guid>888ed0a3-269d-4883-98da-7c3c15eedb48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e032c4-37bf-4ea6-a507-1ed36b9d9c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2d2cc9-3a88-4611-9a18-872caceedb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ea3198-2571-4da4-8322-04c5c42de5f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07743bd-4114-432d-bc6a-7023f190b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b2e96-a401-44e2-8d6f-05d402675be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3f0b32-0b03-4295-a003-b8f0cbece597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d7e190-afba-483e-9cba-7ccc69422b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564ba218-0c9f-42c0-8882-a31dd35ac9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfc8df6-c96b-4f58-82ee-65a2d75fb0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fe48cc8-de15-4e3b-a507-d9516a0e7da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4dd18ab-9fff-47b6-80a2-8b8f74bcd98d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/TestResults/MR-SingleTestCaseScreen-01-20</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6c1dd16d-0bfb-4488-b55c-43b3da4b46c6</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eab7e5af-2121-4ea7-9a4f-23df1ec0e615</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21cc66bb-6699-40b9-b13e-65e6797a5167</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b66073d-76bd-4b6b-89a5-9d83c9d7fa9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>717797b1-fc4c-4a3e-aaaa-16626ab1d4b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d606601-36f1-4ff2-82ff-51c4c9ea04ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de7f8453-1ca8-4bcd-bb31-61253656da2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d139569c-f010-4a92-9f57-8b152bc9e9e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4f56d4e-e09d-4fcd-b189-c3d691e30fc3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab1b3416-4fb7-4b89-aaa6-1b6c8717e62d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c1dd16d-0bfb-4488-b55c-43b3da4b46c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>e41d8f9a-95b1-4877-8e8d-8e357e6e3184</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c1dd16d-0bfb-4488-b55c-43b3da4b46c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>969ecde0-1c3c-41f4-813d-e1ad5ee5da1f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c1dd16d-0bfb-4488-b55c-43b3da4b46c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>5e1c4d74-13fd-41b3-a43c-5f5b8a3244f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6c1dd16d-0bfb-4488-b55c-43b3da4b46c6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>a2a9ec47-4809-4d66-bc2b-8b69c51b962d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0e4af49-9a6e-4358-8e98-1622728fc3a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccfb944b-d1bf-43ab-9efa-ef9dd1116ecf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ef7c1de-71d5-4a18-b1e5-72e07a5533bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba9194fe-d785-474e-95f8-9ff624060904</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28de0c41-aaa8-4104-b805-53204fe96f17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f435fd8f-4f57-4471-b3e6-a2eeaebaf6bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f62e64cd-cf4e-43d0-b97b-cd729f9aa247</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b4a51ab-d1a3-4b2f-b925-c7855fe10c00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad01769b-01b0-46b6-acf7-70e33ad05993</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef47a88b-f3a2-40cc-af33-98ff77d24816</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3d30bd-2722-4c2d-af0b-a978f1fa15f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a748442-e9c9-463a-ad4d-f5245442381d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc0806e7-e251-4d20-a788-4b69cd497048</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>530dbca3-3b08-4bbb-a13b-6731242462db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a0fa97f-8aa5-4466-8b3e-fbe4fc83b7d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>377ea430-590b-4bdf-a4ca-6ec6b3aa0c7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d202cd5d-a84d-4dd1-834f-4f38df0788a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06fbfddf-aa60-4c11-8633-d58009b4f5e9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73013e3d-1adf-422d-8b3d-69308deb1deb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837aecce-1c69-460c-b4ad-06bcaa2dea2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0de0db85-568d-4658-98c6-021784b6710f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc84fdd5-fd69-423a-8fa8-23e6a0d353ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5253d0c-cf07-4ada-b9fa-879f3b75c565</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1975f396-6f4b-4a45-81d0-5392afcc9ab8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0027a483-15cf-4c3f-bb82-081e0192837c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3103e4-2c5e-4cb6-b20a-7094b0f6e657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>93d2d156-e7ff-490b-b6db-793bb09dba85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ac14aa-c678-4f23-93cf-03a3b129225a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17f4f782-dee2-47bf-bcb1-304e95d2238a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3054652f-9447-4fe1-a936-67374315dda8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/TestResults/MR-TestResult-21-28</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c2012db1-9b30-4705-8069-891a4bce96b6</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/CommonBuilds/CommonDataFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7d75d8a-98af-4f53-94eb-8c1b5d08ceeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3fdb34-02e2-48bc-af9d-f292be2b8e09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1a47ff-8a87-443e-b2fb-dfbc9c4116c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b154372-71cc-4ae5-9c97-3278f35906e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55e36130-6fb2-433f-b0e4-c8c1f45f25d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8e0e11-4028-411f-8874-61c622d20fb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b82ef79a-4bde-41f3-926d-be5599b4a003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07d9348c-3e11-45f5-9275-91b6f51a0031</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b89d6e2d-09f1-4bc7-91cf-e1f59636205e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2012db1-9b30-4705-8069-891a4bce96b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>6f874aca-3036-4cef-9ead-fac99554ebb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2012db1-9b30-4705-8069-891a4bce96b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>555eb100-7f73-41ac-b254-c8ebfb2ebb03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2012db1-9b30-4705-8069-891a4bce96b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>9ffae197-9362-4372-81f8-868a5a2cba4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c2012db1-9b30-4705-8069-891a4bce96b6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>1ff59b9e-5c16-4cfe-93bc-f00307c7da14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed7ced5b-af5a-49df-ab53-aca7ba05a231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad9df6fa-116f-4963-804f-335688694c2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5641f0f-fa85-4c27-8a49-5599343afbcf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffe67242-542e-412b-8f53-db343e790a01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f83f077-3290-4376-9b76-b6ea7f1e09fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f196d8e0-8e37-4f7d-ba49-6d8c3d1eade0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d536b8a9-5ea3-4b09-8a4c-468764deec2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8542dbcd-e7fd-4e94-ab07-09c603fb9ada</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>844fe64b-ce1e-4d8c-99df-6c49ef24d44f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d4af78-7efe-4824-9b86-794822ec76c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2588ba4c-3c0b-45b5-9d7f-70bea0517752</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b576cb8f-6257-4af7-a331-afc4ce70b0fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d2dc2f8-780c-48af-9b0b-6f866fa38385</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>569af1a1-9438-4caf-926a-242f0e276b27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a091612-4a2f-4675-9c2c-0000cd119e56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5326c880-ece9-4cf5-8c65-a480cf3fd4f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f940290-ecca-4ca3-aed7-2e33aeb4bd5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5573bba2-0d1f-47b1-8c72-af9ad4cb366d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ad58bad-25f9-44fc-a60e-1c5c00e6e53c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d09a16f-115a-4f4b-8da0-983a68b28779</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3873e5b-1f00-4686-aac5-3a47b11e34ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78bf6303-4e6d-4320-a421-faafd643ef0e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fdfaaf33-eadb-48c0-871e-bb4d353cfb32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Logout/MS-Logout-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f2aec8d-3c65-49d5-91d6-93c6b40697ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0754dcfe-ae83-49b4-b39f-71fe12e6056e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55b6a3ae-e06f-45a7-8952-71c328dfe205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27c728b7-2688-497e-b32e-54a8959bef8b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
