<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RS-Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>74034fbf-9829-4bdd-a992-ba69decc354e</testSuiteGuid>
   <testCaseLink>
      <guid>94036287-63e0-4364-b217-ed5c0f1028fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>64cc689f-0dd5-4ba8-8a8b-cc739b2ac0ec</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-4</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eb63b3b-7d3d-42e8-ae95-c7fac2b18228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7dd234b-945e-42e9-902f-5b698c1bd755</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd1ec7e8-57af-4bb4-a6fe-e6cf13a56635</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a989231-407c-471e-b647-dcfc99308959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d4f7ebc5-402d-4e9e-8569-282d9184ad68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0db515e-7646-4f4a-a7a6-09b0dbf88f9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e18d8c-c553-4e04-b36c-2efa406dad4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25538126-051f-4d24-8fcc-ed59cbb86507</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64cc689f-0dd5-4ba8-8a8b-cc739b2ac0ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>0d4a1218-2009-46be-b261-f212ab1277aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>64cc689f-0dd5-4ba8-8a8b-cc739b2ac0ec</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>6e8a939a-93d0-4e07-aea6-057b851b45db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ca31c29a-016b-429c-ad8c-76af85f310c5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-03</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>35529d4a-2813-472b-b93a-cb536c8cccf7</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab157aaf-45d7-4c9e-9d08-adfec28f8249</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1b7a38c7-7f40-448a-87fa-d6ff27fa1441</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>35529d4a-2813-472b-b93a-cb536c8cccf7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Invalid UserName</value>
         <variableId>2eecf85c-4fbb-4afc-8569-c03a5ca58141</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>35529d4a-2813-472b-b93a-cb536c8cccf7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>4dd8f29b-ce1c-4b15-8309-525fea944dd6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a031035-ea20-430f-8c78-f2ab99e70c14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c786aac4-39ab-4267-b692-4093bc440fae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1837fb90-e402-45eb-a7de-8d0d922965ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ad37b01-625b-444c-a3af-5623f065ac66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8eee7029-a53c-454d-af86-c5ec8aeae5f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e914e51-3755-4f41-8f46-4bc0c29ade3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55262f3b-2d2d-4e3d-9331-f5d4b2826dc3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d440fc0c-07f7-49f6-a41b-313bb9dc5c12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-04</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7f4c5445-3ed9-4189-b6f5-a1b957729ecf</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43f49421-d69f-48d1-96dc-f3fb29c109c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ecd039f-f424-4964-a278-f0627a7f6f12</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f4c5445-3ed9-4189-b6f5-a1b957729ecf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>af53f3fa-d699-44b8-9618-b378c99c4578</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7f4c5445-3ed9-4189-b6f5-a1b957729ecf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>invalidPassword</value>
         <variableId>bbf20744-8991-4598-a4d5-8c331c8d25cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f433fd56-cb15-4a0b-9e18-2734c668c43d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e5d8c4e-ef80-4f14-9c7a-50721c4d646c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d851ea7-301e-4d18-a072-2b9e5bff3250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7327f14-2d26-4b3f-a7cc-9276a36917ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a43b0d2-b663-472e-8f22-e7fe87b38bdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>790e8172-c91d-4390-adf2-a2492d0ef44d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>410bb0da-0d35-4e69-9988-6c174bf98bbe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4d2e242-ea83-4440-886f-f099a3d5ff81</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-05</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d9a8a7f3-0955-47ce-b1d0-b3ae06053125</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>6-6</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60396fa0-cbf8-4e12-902f-a571ae71c1d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf786226-3574-48d4-99a7-fea5846ae108</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9ec8525-206d-4963-9a72-8911c45ad411</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3448740-4cd0-4db2-99f8-694f6d9541ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ed2c0bb-af60-4414-b120-12e124344198</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd3737f3-ce00-4d5a-9972-f051f2e421b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af762d45-823c-4761-9b04-e63c6948d77d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc22079c-da7c-4e1e-b233-094cb2beed1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d9a8a7f3-0955-47ce-b1d0-b3ae06053125</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>bbbacc5c-bd1c-4b6b-9518-32f264d1c4bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d9a8a7f3-0955-47ce-b1d0-b3ae06053125</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>bb6a8f84-27c2-48e7-9fb3-04b51128c362</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f91affd-d969-4fd9-8b81-8448d0f05784</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>44828691-7e86-4f3e-adf1-cf00122158cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-06</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5e363916-1dc8-40f0-a065-d009bf291e68</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>7-7</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e750012b-943c-4136-bcef-80a6f3d0bd5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>299f19dd-cc12-4f9f-90c8-dd4311622f95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9511003-5eec-45e8-af92-b93118598586</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>badb9de6-42be-4949-a6fc-54626c843797</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f23310-2a7d-4e0f-84a1-6e280d514bba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55792ddb-7a73-464b-8e33-95880eb2ec9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21582ad7-a65d-4d87-ab12-3c658f7d8f4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebb41eb4-73be-45b5-9429-7eec4b6cf31b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5e363916-1dc8-40f0-a065-d009bf291e68</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>d0655b6c-f968-47f3-bb48-32e6029ad33b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5e363916-1dc8-40f0-a065-d009bf291e68</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>f1332347-63e9-46ec-8933-b3abc7f07c68</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab214172-0e6e-4d3c-930d-e9bf1944da6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6b22f04-2f7b-45bb-8b40-6cf6f9ace5af</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-07</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>de0f36ae-676e-42cf-b246-c10d4837b9f3</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-8</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>066c5d55-683a-4d4e-85db-fa9033f9f9bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09ad6d04-a84f-4561-9613-1909b8ef569d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d116f006-b2f8-487d-8027-12ce1f669cce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b9c84f5-6406-4f1f-89a5-68c23a56edfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d0e00ef-9043-4811-a8d0-95f64f025549</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>321fa884-1069-40f9-9c27-4aea6b1ffb7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a69fdde-c6ad-4306-8a94-b791103e33a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed4524bc-bdf4-48be-b19f-fc589511c292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de0f36ae-676e-42cf-b246-c10d4837b9f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>6a5eadff-61f2-4df5-baa7-ed2da305d66e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de0f36ae-676e-42cf-b246-c10d4837b9f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>e82ccd51-e9d9-45b9-965e-81d2f899a068</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d1d4a78-b178-4d5a-b37b-9540faa40530</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6714efa-e2b7-402d-b616-dcbad74e1ac2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-Login-08</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52db568a-aa89-423e-9616-df4d1377bdc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6730f347-8fd3-4922-b8b4-d1ff94c06bce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d87f9284-a487-4ebd-a8f2-2a39464f043d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96b76040-e2ab-41d8-acb5-82881eda696f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e111c83f-343e-4517-b47b-8f1753a20095</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a345e524-5f41-4071-9d5c-39c2bfbb2834</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ed63fae-8d17-4cf8-b5a1-1bc6b90fef7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61074cb9-d2a8-4cbb-9bb6-73fb74d84653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83464478-0145-45a2-a0f8-83d919b34be1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b757ad4e-ef5a-4efb-9fd3-a62c77949920</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94c56cec-086c-46d5-b57e-19fc25db009a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cb3f944-aa40-4d41-9d68-38c4454f074b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-ForgotPassword-1-3</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d14b36e-5b45-44ff-84f4-e980d9f87895</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91b50314-e776-47b1-8711-33416ce653bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4df6b4f5-60da-43db-848d-a5ef58eda610</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3d14b36e-5b45-44ff-84f4-e980d9f87895</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>3d00e200-0d34-4230-90ac-ca4efa149113</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1529e582-82d3-426b-9089-8694298ce902</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d20ac1a-f78d-4ce5-add8-38d50547db6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da030248-bfcc-4876-b948-556a3f7e89e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>716055ae-1ef4-4465-b063-ecf42c76ff2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c500c542-b707-47e3-9529-ac428c0b22e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f9da8c7-be1f-4ce6-b10c-5cb6b23e9901</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a167403-2595-49a6-b181-2d92f0ba7c3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f9d87e7-6ee6-45fe-aef6-7c9e6bdf49d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d9bb413-efa2-4d6d-a7fa-01ba7b4284d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c18d7d5-f6b1-498c-a895-6c9cdd7cf05a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57a00e77-46c0-4f12-b38d-daad97b25ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eff5ad64-3a89-4a85-aca5-20ee87459893</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e040a55a-da95-4b1b-b8aa-217b7f220f7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>943fbe91-87ba-4728-a6a5-226e2091b647</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44a30785-26b7-44c2-acbf-7c2bc4225fea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>280624ce-40ca-4067-bd4d-95a9e3ebc5d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e17d716f-b852-4ecd-8cc8-e504ea24399f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e326f1d-dc4f-4df7-99f6-7da4117348a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>815b5768-deec-4df2-97b9-58646bdaee0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-ForgotPassword-4</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827b4e9d-9a7a-49f1-aa11-084e02f4bcca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94fc5d38-482e-4ee4-9f12-390a7186c4c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564a11cb-cbee-4e69-a0e3-b0d0953b8f1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f979f447-fe0e-4947-acd0-03fb185d57d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df2bfa4a-c329-4c9f-ac25-f31a52e9ae48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4772341e-b095-4761-8986-8cff3a4584c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b5ebac-7b83-40bb-8d59-8190e57be627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>096a0da1-f778-4e74-a397-581f84be0212</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd1684b4-1631-4825-982e-3519ab64ed9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18cf8bac-deeb-4b90-a731-ca3d39bce456</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e48f2c6c-e6e0-48e2-97cd-0ae9749d8a72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Regression/Login/MR-OptimizedForChrome-1-5</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d4bd74fe-6b45-4328-9019-3642474d2d07</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Regression/LogIn/Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae722be3-54e0-49b1-bd5b-cab2ae72a673</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4649b42-5447-40da-bac5-de5143e90b3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>001ca505-33d4-465b-8640-16ad622a5e50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8db6485-f2a4-41f1-babb-f548cb61f25d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5458383b-ad94-42a5-a366-ff1f5f66d293</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4644ea94-ee42-47d1-8bdb-8222f56be094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1431639b-8785-4306-934e-df60236e6ed3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d4bd74fe-6b45-4328-9019-3642474d2d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>user</value>
         <variableId>a1d9b31a-b0b3-4d1d-8ad9-6bc36df4b61b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d4bd74fe-6b45-4328-9019-3642474d2d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pass</value>
         <variableId>df9dfea0-ecf7-48c4-a58a-86521aa1f106</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f279e9a-3909-4eb8-9bf7-f5e76ca41fe4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
