<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_100PercentCompleted</name>
   <tag></tag>
   <elementGuidId>ca0c149a-b331-491d-8516-91b4565d7ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@aria-valuenow=&quot;100%&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@aria-valuenow=&quot;100%&quot;]</value>
   </webElementProperties>
</WebElementEntity>
