<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_stopReplay</name>
   <tag></tag>
   <elementGuidId>6a6da819-f7c3-4a2b-b238-87a96a8bfffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@tooltip=&quot;Stop&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@tooltip=&quot;Stop&quot;]</value>
   </webElementProperties>
</WebElementEntity>
