<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chkbox_replay</name>
   <tag></tag>
   <elementGuidId>7872869b-57a1-44c3-be90-99f7e5cef90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@title=&quot;&lt;pChk>&quot;]/parent::div/following-sibling::div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@title=&quot;&lt;pChk>&quot;]/parent::div/following-sibling::div/label</value>
   </webElementProperties>
</WebElementEntity>
