<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dialogue_info</name>
   <tag></tag>
   <elementGuidId>d103a8e0-775a-4468-8fc4-2eb8252f1155</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-test-results-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-test-results-info</value>
   </webElementProperties>
</WebElementEntity>
