<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Passed</name>
   <tag></tag>
   <elementGuidId>587cdce3-b411-40b2-8ba8-99b1e39622a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;textLinks&quot;]/a[contains(text(),&quot;Passed&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;textLinks&quot;]/a[contains(text(),&quot;Passed&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
