<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>list_SelectedDeviceInfo</name>
   <tag></tag>
   <elementGuidId>e3425124-98a2-4751-9a23-fede3cbb03de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;selected&quot;)]/descendant::div[contains(@class,'deviceDetails')]/div[@class='infoText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;selected&quot;)]/descendant::div[contains(@class,'deviceDetails')]/div[@class='infoText']</value>
   </webElementProperties>
</WebElementEntity>
