<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>optionTagReplay29</name>
   <tag></tag>
   <elementGuidId>703128b6-1a26-4a46-a1a3-e13ddb511e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='dropdownWrap']/li[contains(text(),'replay_29')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='dropdownWrap']/li[contains(text(),'replay_29')]</value>
   </webElementProperties>
</WebElementEntity>
