<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Tag</name>
   <tag></tag>
   <elementGuidId>2fabf7a0-37fa-40b9-ba2b-f2b6346ca3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ul[@class='dropdownWrap']/li[contains(text(),&quot;&lt;pTag>&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ul[@class='dropdownWrap']/li[contains(text(),&quot;&lt;pTag>&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
