<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ReplayDeviceOS</name>
   <tag></tag>
   <elementGuidId>a135a027-a71e-47da-b898-578e7a453956</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-test-result-detail/div[2]/div/div/div/div[2]/div[1]/div[2]/div[2]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-test-result-detail/div[2]/div/div/div/div[2]/div[1]/div[2]/div[2]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
