<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ReplayDeviceName</name>
   <tag></tag>
   <elementGuidId>0026c26a-c380-4a46-9d20-7d7d450fb078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-test-result-detail/div[2]/div/div/div/div[2]/div[1]/div[1]/div[1]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-test-result-detail/div[2]/div/div/div/div[2]/div[1]/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
