<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath_listTestCaseSteps</name>
   <tag></tag>
   <elementGuidId>ac7b6e83-f230-460b-8408-12e10efea3f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-card[contains(@Class,'mat-card')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-card[contains(@Class,'mat-card')]</value>
   </webElementProperties>
</WebElementEntity>
