<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Option_RecommendedTests</name>
   <tag></tag>
   <elementGuidId>73ccfc4c-b60c-485c-bffc-d15ad7fb7716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'dropMenu')]/a[contains(text(),'Recommended')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'dropMenu')]/a[contains(text(),'Recommended')]</value>
   </webElementProperties>
</WebElementEntity>
