<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_lastName</name>
   <tag></tag>
   <elementGuidId>896da95e-fc35-42db-8898-caff548f0eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;testDataContainer&quot;]/div[4]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;testDataContainer&quot;]/div[4]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
