<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>address_addressLineTwo</name>
   <tag></tag>
   <elementGuidId>38c15d83-c31b-419c-81c1-f162986a96e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;testDataContainer&quot;]/div[6]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;testDataContainer&quot;]/div[6]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
