<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TestDataRemoveAddress</name>
   <tag></tag>
   <elementGuidId>4d017217-d9fa-455c-b871-c4cb9d3e2230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contentPanelContainer&quot;]/div[2]/app-test-case-data/div[1]/div[2]/div/div[1]/mat-chip/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contentPanelContainer&quot;]/div[2]/app-test-case-data/div[1]/div[2]/div/div[1]/mat-chip/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
