<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>plus_enterUsername</name>
   <tag></tag>
   <elementGuidId>ec604b06-b99e-4f52-bffd-112ab6d63aee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contentPanelContainer&quot;]/div[2]/app-test-case-data/div[8]/div[2]/div/div[2]/span/parent::div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contentPanelContainer&quot;]/div[2]/app-test-case-data/div[8]/div[2]/div/div[2]/span/parent::div</value>
   </webElementProperties>
</WebElementEntity>
