<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_userName</name>
   <tag></tag>
   <elementGuidId>6b2182d6-677c-4cb4-966f-147387f55089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//popover-container/div[2]/app-add-new-test-data/div/div[2]/div[3]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//popover-container/div[2]/app-add-new-test-data/div/div[2]/div[3]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
