<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>var_userLogin</name>
   <tag></tag>
   <elementGuidId>e2399a31-adc4-40e7-94ba-ffdd85f5b6bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;testDataContainer&quot;]/div[2]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;testDataContainer&quot;]/div[2]/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
