<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_JoinNow</name>
   <tag></tag>
   <elementGuidId>70f1a40f-7a28-4de7-81b7-f5907e27b624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*/a/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*/a/strong</value>
   </webElementProperties>
</WebElementEntity>
