<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_OpenSupportEmail</name>
   <tag></tag>
   <elementGuidId>78ebacb5-f03f-481c-afed-a75b783a8c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@title=&quot;Mesmer-Support&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@title=&quot;Mesmer-Support&quot;]</value>
   </webElementProperties>
</WebElementEntity>
