<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>xpath_notification</name>
   <tag></tag>
   <elementGuidId>24604ee8-a4cf-489b-bd42-0651c773ecb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'notification')]/div[contains(@class,'notifyText')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'notification')]/div[contains(@class,'notifyText')]</value>
   </webElementProperties>
</WebElementEntity>
