<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>msg_emailRequired</name>
   <tag></tag>
   <elementGuidId>1827277b-aef5-4d13-8200-04e93e9bff17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//mat-error[@id=&quot;mat-error-0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//mat-error[@id=&quot;mat-error-0&quot;]</value>
   </webElementProperties>
</WebElementEntity>
