<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>commentsTextArea</name>
   <tag></tag>
   <elementGuidId>86512ac5-b51f-4cd7-aebb-0b1b9a8ad390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;mentions-input-box&quot;]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;mentions-input-box&quot;]/textarea</value>
   </webElementProperties>
</WebElementEntity>
