import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import internal.GlobalVariable as GlobalVariable
import com.kms.katalon.core.util.KeywordUtil as KeywordUtil

//MS-Recommended-01 --- All recommended test cases generated by walk.


WebUI.delay(2)
WebUI.callTestCase(findTestCase('TC_AppMap/MS-AppMap-07'), [('ProjectName') : ProjectName, ('BuildNumber') : BuildNumber, ('platformName') : platformName
        , ('Device') : Device, ('RunCrawlOption') : findTestObject('OR_AppMap/optionDropdown_RunCrawl'), ('ThreeDotButton') : findTestObject('OR_AppMap/button_3Dots')
        , ('NoReCrawlButton') : findTestObject('OR_AppMap/button_NoOnRe-Crawl'), ('YesReCrawlButton') : findTestObject('OR_AppMap/button_YesOnRe-Crawl')
        , ('ReCrawlTextonWindow') : findTestObject('OR_AppMap/text_Are you sure you want to re-crawl'), ('CrawlStartedNotification') : findTestObject('OR_AppMap/notification_CrawlStarted')
        , ('CrawlAlreadyInQueueNotification') : findTestObject('OR_AppMap/notification_CrawlAlreadyinQueue'), ('StillCrawlingText') : findTestObject('OR_AppMap/text_StillCrawling')
        , ('xpathString') : xpString, ('projName') : findTestObject('OR_CreateNewTestCase/project_selection'), ('stopCrawlOption') : findTestObject('OR_AppMap/option_StopCrawl')
        , ('DoneCrawlingText') : findTestObject('OR_AppMap/text_DoneCrawling'), ('ConfigCrawl') : findTestObject('OR_AppMap/optionDropdown_ConfigureCrawl')], 
    FailureHandling.STOP_ON_FAILURE)

WebUI.delay(6)
	String testCasesText = WebUI.getText(numberOfTestCasesRun)

	int totalNumberOfTCs = CustomKeywords.'com.mesmer.Utility.extractNumericData'(testCasesText)

	CustomKeywords.'com.mesmer.Utility.goToRecommendedTests'()
	
	String textRecoTCs = WebUI.getText(noOfRecommendedTests)
	int totalNumberOfRecommendedTCs = CustomKeywords.'com.mesmer.Utility.extractNumericData'(textRecoTCs)

	System.err.println("Number of TCs on RECEOMMENDED screen " + totalNumberOfRecommendedTCs)
	
	if(totalNumberOfTCs == totalNumberOfRecommendedTCs){
		KeywordUtil.markPassed("SUCCESS: Total number of TCs from APP MAP screen are matched with Total Number of Recommended TCs")

	}
	else{
		KeywordUtil.markFailed("FAILED: TCs numbers are not matched")
	}
	


