<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_deviceName</name>
   <tag></tag>
   <elementGuidId>d17fbe4f-4274-45de-867c-d1dbdfea41e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(text(),'Baseline')]/parent::div/following-sibling::div/div/div/div/div[4]/span[@class=&quot;deviceName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(text(),'Baseline')]/parent::div/following-sibling::div/div/div/div/div[4]/span[@class=&quot;deviceName&quot;]</value>
   </webElementProperties>
</WebElementEntity>
