<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_AddTag</name>
   <tag></tag>
   <elementGuidId>8afd2cd2-cfea-44e3-ba52-06bbfb222e3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//testcase-tags/div[@class=&quot;tags&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//testcase-tags/div[@class=&quot;tags&quot;]</value>
   </webElementProperties>
</WebElementEntity>
