<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_overlay</name>
   <tag></tag>
   <elementGuidId>29e14135-7de3-4342-9a4f-6a53c565916e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,&quot;displayFlex&quot;)]/mat-card[contains(@class,&quot;noOverlay&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,&quot;displayFlex&quot;)]/mat-card[contains(@class,&quot;noOverlay&quot;)]</value>
   </webElementProperties>
</WebElementEntity>
