<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-BuildUpload</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c89fb3c7-57db-4f03-8dd7-b607ff046628</testSuiteGuid>
   <testCaseLink>
      <guid>3833ac5b-aef0-4655-93f0-360d2c7d1e4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/Login/MS-LogIn-01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0e032c4-37bf-4ea6-a507-1ed36b9d9c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca2d2cc9-3a88-4611-9a18-872caceedb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ea3198-2571-4da4-8322-04c5c42de5f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c07743bd-4114-432d-bc6a-7023f190b276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>585b2e96-a401-44e2-8d6f-05d402675be7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c3f0b32-0b03-4295-a003-b8f0cbece597</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d7e190-afba-483e-9cba-7ccc69422b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>564ba218-0c9f-42c0-8882-a31dd35ac9e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fdfc8df6-c96b-4f58-82ee-65a2d75fb0fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fe48cc8-de15-4e3b-a507-d9516a0e7da7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fe193af5-3776-41b3-a32e-954b7fb1ef5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/BuildUpload/MS-Upload-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e4bcff9a-1b38-4d05-aa57-926e6a176ceb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/BuildUpload/UploadProject</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6fbdb38-9cef-481a-8ebf-12f260123549</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e67d7c6-e739-49c8-bf4f-79c6657cec1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7af8c084-27aa-4f2e-b6b5-91eceebb6f4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f87d8a48-1c6d-4dcd-9c34-99428e2f18d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bd0007b-edfe-4372-86bf-8b9b03d5a7b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e9dc446-3ee1-4936-9d3d-7aa38ec13cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40620016-4cb9-4af3-b97b-f7f2e270e9b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6454921e-1a73-4029-95b2-21da37664b39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>291fcee9-8e2a-4196-b346-1f0c8dfe362c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67800ad3-a10e-4991-99f9-6d32f8857c48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>374284b7-d747-4e43-96b3-28ca798ac58f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>619b9406-28b4-4820-a6d7-a64db4a464d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8db3927-f83f-4507-a9bd-b4cd225b824a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ce6eca5-01e9-4f40-a4a4-88b6ad558834</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2813417c-8bc2-4c36-bc9c-2807d8722545</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd34374f-3f0f-4ef0-95fa-049d07644099</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dedac394-598e-4a45-9640-12da94e33b4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86c5f7d8-70a0-4bcf-95b2-3fec0d7a9a00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9620afa1-ea04-4b2b-a9a7-f095275aac94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f04b37f-2079-4d82-8e0c-0b067e6c8475</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1cebd8e-dd82-4c01-b247-814b4ad3a7ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fce6a914-439e-43dc-aa89-070ba168ab2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8c5b91-fc0c-469d-9a19-292fd3c63d6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e4bcff9a-1b38-4d05-aa57-926e6a176ceb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildName</value>
         <variableId>05185788-b49e-46d5-8681-008931d1773f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8648d20-da68-4141-8946-53ab8b4797e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91fd8080-1925-4740-b04e-dc278c0107f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8955c654-a01a-4295-bdb7-9a07b6178236</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c60e3b3-db8f-4a6f-a610-3d4acc13b169</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>230c3615-1b5e-43bf-af31-a35ba81b4f7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7594b732-460e-47e3-b42a-46a877bde45f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>709eaa57-dc8c-4ac3-a9c1-217621349353</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ff1e712-6e15-43c3-b1cb-a4126870215c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/BuildUpload/MS-Upload-02</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>55959c51-9aee-4fb5-8b7c-08fab70c9d07</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/BuildUpload/BuildUpload</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>293cd81e-39de-42f8-a15a-b694c6653959</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58a0c22e-9275-4374-9ee0-6d857d647fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e3f07f8-a2c6-4686-8d13-78b58d31c8e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c5100a-100b-4a75-8b6f-bfe54da4dbf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50bafd5c-4eb2-4ee4-a36f-783cb8314c5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>867ae82c-36de-4c83-be6c-d16473f95729</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44368119-fe83-4b52-990e-ef535a046f94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b810384-24fb-4562-b4d6-52f10649c753</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57caa15a-bb71-4c18-96d8-5a81cbd105eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ab48f8-e78c-44b6-826e-d57e715cbc0a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>903ee25d-52e4-4656-bd93-10914f8b3601</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed985cc9-e9be-4ccb-b4cb-f33dfcae0837</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed18ef41-9c05-49b6-91a8-da24a29315d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2557a9f-c22f-4dfb-9c33-abdb159f98eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9687c9c-bad8-4523-8174-ddec084b3a15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f09207d8-5e94-4ab7-ad65-d12d5cf345db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>768d097e-229e-46f1-b69c-cb58f31c0131</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2edff1fc-318a-4688-a4a0-b1804dc124aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8440cc5-0f82-4aa6-87f0-eac7d97cddcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b49ef983-db9d-4866-8930-bd3a519dba37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55959c51-9aee-4fb5-8b7c-08fab70c9d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProjectName</value>
         <variableId>a2ff5494-c70a-466b-9f37-fb31e9e1fd88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55959c51-9aee-4fb5-8b7c-08fab70c9d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>BuildNumber</value>
         <variableId>2e2df1c9-2666-479e-a4eb-e417f3be77b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55959c51-9aee-4fb5-8b7c-08fab70c9d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>platformName</value>
         <variableId>bb658a99-20b3-4110-82ae-a53b2ab5151f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55959c51-9aee-4fb5-8b7c-08fab70c9d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Device</value>
         <variableId>7153e16b-a23d-48ae-96b3-1ff85fc4bdf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaf8f18e-da46-490c-b36a-4246920384df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0bf7fd8-7fe9-4e3b-bd53-2c5f31e43f3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0af1fdd8-bdb2-4c06-a7a3-194a7b556f22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4385968c-82c3-4a36-bc14-12bf9687bc30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0398e822-65a6-45e7-bb8c-63466142c53b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f55b668-e568-48ff-a395-2c17539b400f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e21079f7-de15-4573-9636-bc21fc1330c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>693a0ad1-3394-48ad-b446-ada0a4c366f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a279fda-b096-4fd5-8876-5c3ddbd188f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>597007f3-9441-4dd6-90b5-dc7896a728df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe03cd2-0026-4fca-bd40-eb49c1e01a55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269edd67-5aa9-4d23-8d2c-e41e6aa8e0e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>821899fe-0cfd-4f91-904a-38fe3305fcd4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55959c51-9aee-4fb5-8b7c-08fab70c9d07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildName</value>
         <variableId>ef6ff4fb-4cdf-43ea-8f85-c1f27796b896</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941b0190-248c-432d-a68e-9ab723e219fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98bc566d-2ecd-4548-a8bd-35049c1a59a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Mesmer_Sanity/BuildUpload/MS-Upload-03</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9cffef57-0a64-48d6-a485-96d90a3a43a8</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/DF_Sanity/BuildUpload/UploadProject</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10224403-50dd-44e3-a9e3-7360155c3c1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e15cfd1-8ab7-40f2-89c6-d4076ec6928d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c82a2d51-1102-479b-a308-4548e1da7dad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48523886-0454-43d3-a14e-d238260a9101</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11c1d073-2fa2-4e55-886e-cee1ef97af95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27943d6c-1c7d-43f7-a738-f72d5a335d60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43b30b96-6587-4978-a1c5-b2f755ad0ca0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>971b9a2f-884e-461b-9fec-6445e12e8083</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ab75ed0-86cc-4ab7-af07-d5f604369318</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c29748bd-4e41-4cfd-bf91-8dfdd7eeaa59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67092cc1-b08b-423b-a2e9-d27d14d250f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d389654-ff7c-4b85-ad59-0232ba3c25e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f20754a-025a-4d3d-b183-50106eec5291</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f3be237-8f6c-499a-b98c-3e9fe616b0ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a2ec1f5-1ae4-4d54-a202-7d949c6a3f2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48ea62dc-11a5-4021-b0ef-693b13321011</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ea907d5-d97d-4077-9718-88732c19b358</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c369bf47-0c8d-4de3-9583-4b11225c861a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02956bf5-eb37-4999-870f-243376b918cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>582519e0-fdba-4a77-9ffa-c241b1363cbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd89253a-df3b-476e-ba75-b3a555efda00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>853d5549-5b52-4293-b0d3-1dc049dd9c44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17cf6fc7-a4b7-4928-ae72-2c8d76b83ff9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e004123f-b2b4-49d7-9521-c68769822fdc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a02794d1-6f6b-493e-ba9e-648b40430293</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17ed01ab-cb2e-4052-8e7f-88c03ead48b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9cffef57-0a64-48d6-a485-96d90a3a43a8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>buildName</value>
         <variableId>9856aa23-4f40-4b2d-a636-fd325f274044</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>729476d1-d267-407a-a13f-cf1c8e7bf7d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>654313ec-9feb-4b7a-b695-82358eb370a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b1c2bc8-4fe5-407e-acec-cdfe32a13dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fcc5a03e-0c1c-4a68-8ffe-7bc34e574798</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14fb87a3-6cd8-465b-a7b0-ff626d4a6995</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>254acff7-0ce7-46e7-a93b-cf7acb18cd5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>416a0571-b714-401a-96a8-21643cd29ef5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96f8795a-236e-4f0a-936d-c80001b93075</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
