<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_reRun_1</name>
   <tag></tag>
   <elementGuidId>1c0e8115-aac8-4959-8d38-ca21479bb05d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='actionItems']/a[@title='Rerun']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='actionItems']/a[@title='Rerun']</value>
   </webElementProperties>
</WebElementEntity>
