<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_DeviceConnected_1</name>
   <tag></tag>
   <elementGuidId>f6b4363b-4113-4188-87ad-4909f04d0dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class,'completed')]/div[contains(text(),'Connected')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[contains(@class,'completed')]/div[contains(text(),'Connected')]</value>
   </webElementProperties>
</WebElementEntity>
