<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_error_1</name>
   <tag></tag>
   <elementGuidId>1744e816-12e9-4f7d-97cc-dfbd4b72a98e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class=&quot;errorMsgWrap&quot;]/ancestor::mat-card/preceding::mat-card[1]/descendant::div[@class=&quot;screenContent&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class=&quot;errorMsgWrap&quot;]/ancestor::mat-card/preceding::mat-card[1]/descendant::div[@class=&quot;screenContent&quot;]</value>
   </webElementProperties>
</WebElementEntity>
